<?php
/**
 * @file
 * Code for the Pipeline feature.
 */

include_once 'pipeline.features.inc';

/**
* Implements hook_views_api_alter().
* REF. https://goo.gl/mp2yt0
* Views api is specified by features but we want to add the template directory to it.
*/
function pipeline_views_api_alter(&$apis) {
  // Fetches the view templates
  if (!empty($apis['pipeline']) && $apis['pipeline']['api'] == '3.0') {
  $apis['pipeline']['template path'] = drupal_get_path('module', 'pipeline') . '/templates';
  }
}
/**
 * Implements hook_theme().
 */
function pipeline_theme($existing, $type, $theme, $path) {
  // Fetching the node templates
  $theme = array();
  $theme['node__development_candidate'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--development-candidate',
    'path' => drupal_get_path('module', 'pipeline') . '/templates',
   );
  return $theme;
}
/**
* Implementation of hook_init().
*/
function pipeline_init() {
  // Add JavaScript
  drupal_add_js(drupal_get_path('module', 'pipeline') . '/js/isotope.pkgd.min.js');
  drupal_add_js(drupal_get_path('module', 'pipeline') . '/js/script.js');
  // Add CSS
  drupal_add_css(drupal_get_path('module', 'pipeline') . '/css/pipeline.css');
}




